# Generated by Django 6.0.5 on 2026-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Calificación'),
        ),
    ]
